#![allow(dead_code)]

use std::collections::{BTreeMap, HashSet};
use std::path::{Component, Path, PathBuf};

use serde::Deserialize;
use sha2::{Digest, Sha256};

#[derive(Debug, Deserialize)]
pub struct RnsFixtureIndex {
    pub schema_version: u32,
    pub authorities: BTreeMap<String, RnsAuthority>,
    pub vectors: Vec<RnsVector>,
    #[serde(skip)]
    root: PathBuf,
}

#[derive(Debug, Deserialize)]
pub struct RnsAuthority {
    pub repository: String,
    pub revision: String,
    pub release: String,
}

#[derive(Debug, Deserialize)]
pub struct RnsVector {
    pub id: String,
    pub authority_id: String,
    pub kind: String,
    pub artifact: String,
    pub sha256: String,
    pub generator: String,
    pub source_symbols: Vec<String>,
    pub expected: serde_json::Value,
}

pub fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../..")
}

/// Root directory containing JSON fixture files generated by the Python
/// test-vector generator (`tests/interop/python/generate_fixtures.py`).
pub fn fixtures_dir() -> PathBuf {
    repo_root().join("tests").join("interop").join("fixtures")
}

fn is_repository_relative(path: &Path) -> bool {
    !path.is_absolute() && path.components().all(|part| matches!(part, Component::Normal(_)))
}

pub fn load_rns_index() -> Result<RnsFixtureIndex, Vec<String>> {
    let root = repo_root();
    load_rns_index_from(&root, &root.join("tests/interop/fixtures/rns/index-v2.json"))
}

pub fn load_rns_index_from(root: &Path, path: &Path) -> Result<RnsFixtureIndex, Vec<String>> {
    let data = std::fs::read_to_string(path)
        .map_err(|error| vec![format!("failed to read {}: {error}", path.display())])?;
    let mut index: RnsFixtureIndex = serde_json::from_str(&data)
        .map_err(|error| vec![format!("failed to parse {}: {error}", path.display())])?;
    let mut errors = Vec::new();
    if index.schema_version != 2 {
        errors.push(format!("{}: unsupported schema version", path.display()));
    }
    if index.authorities.is_empty() {
        errors.push(format!("{}: authorities must not be empty", path.display()));
    }
    for (id, authority) in &index.authorities {
        if authority.repository.is_empty() || authority.release.is_empty() {
            errors.push(format!("{id}: authority metadata must not be empty"));
        }
        if authority.revision.len() != 40
            || !authority
                .revision
                .bytes()
                .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
        {
            errors.push(format!("{id}: revision must be a lowercase full commit SHA"));
        }
    }
    let mut ids = HashSet::new();
    for vector in &index.vectors {
        if vector.id.is_empty() || !ids.insert(vector.id.as_str()) {
            errors.push(format!("{}: missing or duplicate vector id", vector.id));
        }
        if !index.authorities.contains_key(&vector.authority_id) {
            errors.push(format!("{}: unknown authority {}", vector.id, vector.authority_id));
        }
        if vector.kind.is_empty() {
            errors.push(format!("{}: kind must not be empty", vector.id));
        }
        let artifact = Path::new(&vector.artifact);
        if !is_repository_relative(artifact) {
            errors.push(format!("{}: artifact must be repository-relative", vector.id));
        } else {
            match std::fs::read(root.join(artifact)) {
                Ok(bytes) => {
                    if hex::encode(Sha256::digest(bytes)) != vector.sha256 {
                        errors.push(format!("{}: artifact digest mismatch", vector.id));
                    }
                }
                Err(error) => {
                    errors.push(format!("{}: artifact cannot be read: {error}", vector.id))
                }
            }
        }
        let generator = Path::new(&vector.generator);
        if vector.generator != "manual-copy"
            && (!is_repository_relative(generator) || !root.join(generator).is_file())
        {
            errors.push(format!("{}: generator does not exist", vector.id));
        }
        if vector.source_symbols.is_empty()
            || vector.source_symbols.iter().any(|symbol| symbol.is_empty())
        {
            errors.push(format!("{}: source symbols must not be empty", vector.id));
        }
        if vector
            .expected
            .as_object()
            .and_then(|value| value.get("type"))
            .and_then(|value| value.as_str())
            .is_none_or(str::is_empty)
        {
            errors.push(format!("{}: expected outcome must have a type", vector.id));
        }
    }
    if index.vectors.is_empty() {
        errors.push(format!("{}: vectors must not be empty", path.display()));
    }
    if errors.is_empty() {
        index.root = root.to_path_buf();
        Ok(index)
    } else {
        Err(errors)
    }
}

pub fn rns_vector<'a>(index: &'a RnsFixtureIndex, id: &str) -> Result<&'a RnsVector, String> {
    index
        .vectors
        .iter()
        .find(|vector| vector.id == id)
        .ok_or_else(|| format!("unknown RNS fixture vector {id}"))
}

pub fn load_rns_vector_bytes(index: &RnsFixtureIndex, id: &str) -> Result<Vec<u8>, String> {
    let vector = rns_vector(index, id)?;
    let bytes = std::fs::read(index.root.join(&vector.artifact))
        .map_err(|error| format!("failed to read vector {id}: {error}"))?;
    let digest = hex::encode(Sha256::digest(&bytes));
    if digest != vector.sha256 {
        return Err(format!("fixture digest mismatch for {id}"));
    }
    Ok(bytes)
}

/// Load a JSON fixture file and deserialise it into `T`.
pub fn load_fixture<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = fixtures_dir().join(filename);
    let data = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture {}: {e}", path.display()));
    serde_json::from_str(&data)
        .unwrap_or_else(|e| panic!("failed to parse fixture {}: {e}", path.display()))
}

/// Decode a hex string to bytes.
pub fn hex_decode(s: &str) -> Vec<u8> {
    hex::decode(s).unwrap_or_else(|e| panic!("invalid hex string '{s}': {e}"))
}
