use std::path::{Path, PathBuf};

/// Root directory containing JSON fixture files generated by the Python
/// test-vector generator (`tests/interop/python/generate_fixtures.py`).
pub fn fixtures_dir() -> PathBuf {
    // tests/common/mod.rs  →  tests/  →  crate root  →  repo root  →  tests/interop/fixtures
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..") // crates/libs/
        .join("..") // crates/
        .join("..") // repo root
        .join("tests")
        .join("interop")
        .join("fixtures")
}

/// Load a JSON fixture file and deserialise it into `T`.
pub fn load_fixture<T: serde::de::DeserializeOwned>(filename: &str) -> T {
    let path = fixtures_dir().join(filename);
    let data = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture {}: {e}", path.display()));
    serde_json::from_str(&data)
        .unwrap_or_else(|e| panic!("failed to parse fixture {}: {e}", path.display()))
}

/// Decode a hex string to bytes.
pub fn hex_decode(s: &str) -> Vec<u8> {
    hex::decode(s).unwrap_or_else(|e| panic!("invalid hex string '{s}': {e}"))
}
