//! Canonical NomadNet request and response fixtures.
//!
//! `tests/interop/fixtures/nomadnet-v1` is generated by executing the pinned
//! Python NomadNet node handlers and RNS request packing
//! (`tests/interop/python/generate_nomadnet_fixtures.py`). These tests replay
//! the same page tree, identities, link id, and submitted fields through the
//! Rust native host and request layer and require byte-identical results.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use rns_core::destination::request_path_hash;
use rns_core::hash::AddressHash;
use rns_core::identity::Identity;
use rns_core::transport::request::{
    decode_response_envelope, encode_raw_response, encode_request_envelope,
    encode_response_envelope,
};
use sha2::{Digest, Sha256};
use styrened::services::pages::PageService;

const NOMADNET_REVISION: &str = "ad10301569a39d4f43b3d21ae9fc392602c937ca";
const RNS_REVISION: &str = "b48b96e61676504e0a4e527b33b9a0b4495c6872";

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../..")
}

fn fixture_root() -> PathBuf {
    workspace_root().join("tests/interop/fixtures/nomadnet-v1")
}

fn index() -> serde_json::Value {
    let text = std::fs::read_to_string(fixture_root().join("index.json")).expect("read index");
    serde_json::from_str(&text).expect("parse index")
}

fn artifact(name: &str) -> Vec<u8> {
    std::fs::read(fixture_root().join(name)).unwrap_or_else(|error| panic!("read {name}: {error}"))
}

fn vector<'a>(index: &'a serde_json::Value, id: &str) -> &'a serde_json::Value {
    index["vectors"]
        .as_array()
        .expect("vectors")
        .iter()
        .find(|vector| vector["id"] == id)
        .unwrap_or_else(|| panic!("missing vector {id}"))
}

fn text<'a>(value: &'a serde_json::Value, key: &str) -> &'a str {
    value[key].as_str().unwrap_or_else(|| panic!("{key} must be a string"))
}

fn hex_bytes(value: &str) -> Vec<u8> {
    hex::decode(value).expect("hex")
}

fn address(value: &str) -> AddressHash {
    let bytes: [u8; 16] = hex_bytes(value).try_into().expect("16-byte hash");
    AddressHash::new(bytes)
}

fn identity(index: &serde_json::Value, label: &str) -> Identity {
    let record = &index["parameters"]["identities"][label];
    let public = hex_bytes(text(record, "public_key_hex"));
    assert_eq!(public.len(), 64, "Python get_public_key yields x25519 and ed25519 keys");
    let identity = Identity::new_from_slices(&public[..32], &public[32..]);
    assert_eq!(
        hex::encode(identity.address_hash.as_slice()),
        text(record, "hash_hex"),
        "Rust identity hash must match the Python identity hash for {label}"
    );
    identity
}

/// Materialize the fixture page tree exactly as the generator staged it for the
/// Python node: sources under `pages/`, `.allowed` lists beside them, the
/// dynamic page executable, and the file under `files/`.
fn stage_tree(index: &serde_json::Value, root: &Path) -> PageService {
    let pages = root.join("pages");
    let files = root.join("files");
    std::fs::create_dir_all(&pages).expect("pages dir");
    std::fs::create_dir_all(&files).expect("files dir");
    for page in index["parameters"]["pages"].as_array().expect("pages") {
        let request_path = text(page, "request_path");
        let name = request_path.strip_prefix("/page/").expect("page path");
        let source = text(page, "source");
        let target = pages.join(name);
        std::fs::write(&target, artifact(source)).expect("write page");
        let executable =
            vector(index, &format!("nomadnet-source-{source}"))["expected"]["executable"]
                .as_bool()
                .expect("executable flag");
        if executable {
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                std::fs::set_permissions(&target, std::fs::Permissions::from_mode(0o755))
                    .expect("chmod dynamic page");
            }
        }
        if let Some(allowed) = page["allowed"].as_str() {
            std::fs::write(pages.join(format!("{name}.allowed")), artifact(allowed))
                .expect("write allow list");
        }
    }
    for file in index["parameters"]["files"].as_array().expect("files") {
        let name = text(file, "request_path").strip_prefix("/file/").expect("file path");
        std::fs::write(files.join(name), artifact(text(file, "source"))).expect("write file");
    }
    PageService::with_storage_dirs(pages, files)
}

fn entry(service: &PageService, request_path: &str) -> styrened::services::NativePageEntry {
    service
        .native_entries()
        .into_iter()
        .find(|entry| entry.request_path == request_path)
        .unwrap_or_else(|| panic!("missing native entry {request_path}"))
}

#[test]
fn fixture_index_is_pinned_and_every_digest_matches() {
    let index = index();
    assert_eq!(index["schema_version"], 2);
    assert_eq!(index["authorities"]["nomadnet-1.2.3"]["revision"], NOMADNET_REVISION);
    assert_eq!(index["authorities"]["rns-1.4.2"]["revision"], RNS_REVISION);
    let vectors = index["vectors"].as_array().expect("vectors");
    assert!(vectors.len() >= 20, "fixture set must cover sources, requests, responses, and files");
    for vector in vectors {
        let path = workspace_root().join(text(vector, "artifact"));
        let digest = hex::encode(Sha256::digest(std::fs::read(&path).expect("artifact")));
        assert_eq!(digest, text(vector, "sha256"), "digest mismatch for {}", path.display());
        assert!(index["authorities"][text(vector, "authority_id")].is_object());
    }
}

#[test]
fn request_envelopes_match_pinned_link_request_packing() {
    let index = index();
    for label in ["index", "dynamic", "private", "secret", "file"] {
        let vector = vector(&index, &format!("rns-request-{label}"));
        let expected = &vector["expected"];
        let path = text(expected, "path");
        let path_hash = request_path_hash(path);
        assert_eq!(hex::encode(path_hash), text(expected, "path_hash_hex"), "{path}");
        let requested_at = expected["requested_at"].as_f64().expect("requested_at");
        let data = hex_bytes(text(expected, "data_hex"));
        let envelope =
            encode_request_envelope(requested_at, path_hash, &data).expect("request envelope");
        let artifact = artifact(&format!("request_{label}.msgpack"));
        assert_eq!(envelope, artifact, "request envelope for {path}");
        let request_id = &Sha256::digest(&envelope)[..16];
        assert_eq!(hex::encode(request_id), text(expected, "request_id_hex"), "{path}");
    }
}

#[test]
fn response_envelope_matches_pinned_handle_request_packing() {
    let index = index();
    let vector = vector(&index, "rns-response-envelope-index");
    let request_id: [u8; 16] =
        hex_bytes(text(&vector["expected"], "request_id_hex")).try_into().expect("request id");
    let content = artifact(text(&vector["expected"], "response_artifact"));
    let binary = encode_raw_response(&content).expect("binary response");
    let envelope = encode_response_envelope(request_id, &binary).expect("response envelope");
    let artifact = artifact("response_envelope_index.msgpack");
    assert_eq!(envelope, artifact);
    assert_eq!(decode_response_envelope(&artifact), Ok((request_id, binary)));
}

#[test]
fn static_pages_files_and_allow_lists_follow_pinned_node_policy() {
    let index = index();
    let root = tempfile::tempdir().expect("tree root");
    let service = stage_tree(&index, root.path());
    let allowed = identity(&index, "allowed");
    let denied = identity(&index, "denied");
    let link_id = address(text(&index["parameters"], "link_id_hex"));

    let public = entry(&service, "/page/index.mu");
    assert!(public.allowed_identities.is_none(), "index.mu has no allow list");
    assert_eq!(
        service.serve_native(&public, &[0xc0], Some(&allowed), link_id).expect("static page"),
        artifact("response_index.bin")
    );

    let private = entry(&service, "/page/private.mu");
    let policy = private.allowed_identities.clone().expect("private.mu allow list");
    assert_eq!(policy, BTreeSet::from([allowed.address_hash]));
    assert!(!policy.contains(&denied.address_hash));
    assert_eq!(
        service.serve_native(&private, &[0xc0], Some(&allowed), link_id).expect("allowed page"),
        artifact("response_private_allowed.bin")
    );

    let secret = entry(&service, "/page/secret.mu");
    let policy = secret.allowed_identities.clone().expect("secret.mu allow list");
    assert_eq!(policy, BTreeSet::from([AddressHash::new([0; 16])]));
    assert!(!policy.contains(&allowed.address_hash));

    // The Python node answers a denied request with its fixed denial page.
    // The Rust host denies at the request registry instead; the Rust client
    // must recognise this page when a Python node returns it.
    let denial = artifact("response_private_denied.bin");
    assert_eq!(artifact("response_private_anonymous.bin"), denial);
    assert_eq!(artifact("response_secret_denied.bin"), denial);
    assert!(denial.starts_with(b">Request Not Allowed\n"));
    assert_ne!(denial, artifact("response_private_allowed.bin"));

    let file = entry(&service, "/file/manual.bin");
    assert!(file.allowed_identities.is_none());
    assert_eq!(
        service.serve_native(&file, &[0xc0], Some(&allowed), link_id).expect("file"),
        artifact("file_manual.bin")
    );
}

#[cfg(unix)]
#[test]
fn dynamic_page_receives_pinned_identity_link_and_fields() {
    let index = index();
    let root = tempfile::tempdir().expect("tree root");
    let service = stage_tree(&index, root.path());
    let allowed = identity(&index, "allowed");
    let link_id = address(text(&index["parameters"], "link_id_hex"));
    let request = vector(&index, "rns-request-dynamic");
    let data = hex_bytes(text(&request["expected"], "data_hex"));

    let dynamic = entry(&service, "/page/dynamic.mu");
    let output =
        service.serve_native(&dynamic, &data, Some(&allowed), link_id).expect("dynamic page");
    let expected = artifact("response_dynamic.bin");
    assert_eq!(String::from_utf8_lossy(&output), String::from_utf8_lossy(&expected));

    // The page script echoes every environment entry the Python node set, so
    // each one must appear verbatim in the Rust output as well.
    let environment = &vector(&index, "nomadnet-response-dynamic")["expected"]["environment"];
    let rendered = String::from_utf8_lossy(&output);
    for (name, value) in environment.as_object().expect("environment") {
        let key = match name.as_str() {
            "remote_identity" => "remote",
            "link_id" => "link",
            other => other,
        };
        let expected_line = format!("{key}={}\n", value.as_str().expect("value"));
        assert!(rendered.contains(&expected_line), "dynamic output must carry {expected_line:?}");
    }
}

#[test]
fn file_metadata_matches_pinned_resource_framing() {
    let index = index();
    let vector = vector(&index, "rns-file-metadata");
    let packed = artifact("file_metadata.msgpack");
    let decoded = rmpv::decode::read_value(&mut std::io::Cursor::new(&packed)).expect("metadata");
    let rmpv::Value::Map(entries) = decoded else { panic!("metadata must be a map") };
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].0, rmpv::Value::from("name"));
    assert_eq!(
        entries[0].1,
        rmpv::Value::Binary(text(&vector["expected"], "name").as_bytes().to_vec())
    );

    let length = u32::try_from(packed.len()).expect("length");
    let mut prefix = length.to_be_bytes()[1..].to_vec();
    prefix.extend_from_slice(&packed);
    assert_eq!(hex::encode(&prefix), text(&vector["expected"], "resource_prefix_hex"));

    let raw = artifact(text(&vector["expected"], "raw_data_artifact"));
    let binary = encode_raw_response(&raw).expect("binary");
    let value = rmpv::decode::read_value(&mut std::io::Cursor::new(&binary)).expect("binary value");
    assert_eq!(value, rmpv::Value::Binary(raw));
}
