use super::*;

#[test]
fn sdk_rpc_core_schema_valid_fixtures_pass_contract_checks() {
    let schemas = load_rpc_core_schemas();

    assert_schema_valid(
        &schemas.sdk_negotiate_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_negotiate_v2.request.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_negotiate_v2.request.valid.json"),
    );
    assert_schema_valid(
        &schemas.sdk_negotiate_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_negotiate_v2.response.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_negotiate_v2.response.valid.json"),
    );
    assert_schema_valid(
        &schemas.sdk_send_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_send_v2.request.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_send_v2.request.valid.json"),
    );
    assert_schema_valid(
        &schemas.sdk_send_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_send_v2.response.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_send_v2.response.valid.json"),
    );
    assert_schema_valid(
        &schemas.sdk_status_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_status_v2.request.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_status_v2.request.valid.json"),
    );
    assert_schema_valid(
        &schemas.sdk_status_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_status_v2.response.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_status_v2.response.valid.json"),
    );
    assert_schema_valid(
        &schemas.sdk_configure_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_configure_v2.request.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_configure_v2.request.valid.json"),
    );
    assert_schema_valid(
        &schemas.sdk_configure_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_configure_v2.response.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_configure_v2.response.valid.json"),
    );
    assert_schema_valid(
        &schemas.sdk_poll_events_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_poll_events_v2.request.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_poll_events_v2.request.valid.json"),
    );
    assert_schema_valid(
        &schemas.sdk_poll_events_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_poll_events_v2.response.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_poll_events_v2.response.valid.json"),
    );
    assert_schema_valid(
        &schemas.sdk_cancel_message_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_cancel_message_v2.request.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_cancel_message_v2.request.valid.json"),
    );
    assert_schema_valid(
        &schemas.sdk_cancel_message_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_cancel_message_v2.response.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_cancel_message_v2.response.valid.json"),
    );
    assert_schema_valid(
        &schemas.sdk_snapshot_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_snapshot_v2.request.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_snapshot_v2.request.valid.json"),
    );
    assert_schema_valid(
        &schemas.sdk_snapshot_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_snapshot_v2.response.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_snapshot_v2.response.valid.json"),
    );
    assert_schema_valid(
        &schemas.sdk_shutdown_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_shutdown_v2.request.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_shutdown_v2.request.valid.json"),
    );
    assert_schema_valid(
        &schemas.sdk_shutdown_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_shutdown_v2.response.valid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_shutdown_v2.response.valid.json"),
    );
}

#[test]
fn sdk_rpc_core_schema_invalid_fixtures_are_rejected() {
    let schemas = load_rpc_core_schemas();

    assert_schema_invalid(
        &schemas.sdk_negotiate_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_negotiate_v2.request.invalid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_negotiate_v2.request.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.sdk_send_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_send_v2.request.invalid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_send_v2.request.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.sdk_status_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_status_v2.request.invalid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_status_v2.request.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.sdk_configure_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_configure_v2.request.invalid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_configure_v2.request.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.sdk_poll_events_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_poll_events_v2.request.invalid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_poll_events_v2.request.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.sdk_cancel_message_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_cancel_message_v2.request.invalid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_cancel_message_v2.request.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.sdk_snapshot_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_snapshot_v2.request.invalid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_snapshot_v2.request.invalid.json"),
    );
    assert_schema_invalid(
        &schemas.sdk_shutdown_v2,
        "docs/fixtures/sdk-v2/rpc/sdk_shutdown_v2.request.invalid.json",
        &fixture("docs/fixtures/sdk-v2/rpc/sdk_shutdown_v2.request.invalid.json"),
    );
}
