#!/usr/bin/env bash
set -euo pipefail

scorecard_path="${RELEASE_SCORECARD_JSON_PATH:-target/release-scorecard/release-scorecard.json}"
out_dir="${CANARY_OUT_DIR:-target/release-readiness}"
report_json="${CANARY_REPORT_JSON_PATH:-${out_dir}/canary-criteria-report.json}"
report_md="${CANARY_REPORT_MD_PATH:-${out_dir}/canary-criteria-report.md}"

min_security_pass_rows="${CANARY_MIN_SECURITY_PASS_ROWS:-8}"
max_soak_failures="${CANARY_MAX_SOAK_FAILURES:-0}"
max_mesh_failures="${CANARY_MAX_MESH_FAILURES:-0}"
min_supply_chain_artifacts="${CANARY_MIN_SUPPLY_CHAIN_ARTIFACTS:-1}"

fail() {
  echo "canary criteria check failed: $*" >&2
  exit 1
}

require_file() {
  local path="$1"
  [ -f "$path" ] || fail "required file missing: $path"
}

require_command() {
  local cmd="$1"
  command -v "$cmd" >/dev/null || fail "required command missing: $cmd"
}

check_status() {
  local label="$1"
  local ok="$2"
  if [ "$ok" != "1" ]; then
    failures+=("$label")
  fi
}

require_command jq
require_file "$scorecard_path"

overall_status="$(jq -r '.overall_status // "UNKNOWN"' "$scorecard_path")"
performance_status="$(jq -r '.performance_status // "UNKNOWN"' "$scorecard_path")"
soak_status="$(jq -r '.soak_status // "unknown"' "$scorecard_path")"
soak_failures="$(jq -r '.soak_failures // 0' "$scorecard_path")"
mesh_failures="$(jq -r '.soak_mesh_failures // 0' "$scorecard_path")"
security_pass_rows="$(jq -r '.security_pass_rows // 0' "$scorecard_path")"
supply_chain_artifact_count="$(jq -r '.supply_chain_artifact_count // 0' "$scorecard_path")"

failures=()

check_status "overall_status=PASS" "$([ "$overall_status" = "PASS" ] && echo 1 || echo 0)"
check_status "performance_status=PASS" "$([ "$performance_status" = "PASS" ] && echo 1 || echo 0)"
check_status "soak_status=pass" "$([ "$soak_status" = "pass" ] && echo 1 || echo 0)"
check_status "soak_failures<=${max_soak_failures}" "$([ "$soak_failures" -le "$max_soak_failures" ] && echo 1 || echo 0)"
check_status "soak_mesh_failures<=${max_mesh_failures}" "$([ "$mesh_failures" -le "$max_mesh_failures" ] && echo 1 || echo 0)"
check_status "security_pass_rows>=${min_security_pass_rows}" "$([ "$security_pass_rows" -ge "$min_security_pass_rows" ] && echo 1 || echo 0)"
check_status "supply_chain_artifact_count>=${min_supply_chain_artifacts}" "$([ "$supply_chain_artifact_count" -ge "$min_supply_chain_artifacts" ] && echo 1 || echo 0)"

mkdir -p "$out_dir"

if [ "${#failures[@]}" -eq 0 ]; then
  status="PASS"
else
  status="FAIL"
fi

failure_json="[]"
if [ "${#failures[@]}" -gt 0 ]; then
  failure_json="$(printf '%s\n' "${failures[@]}" | jq -R . | jq -s .)"
fi

cat > "$report_json" <<EOF
{
  "status": "$status",
  "scorecard_path": "$scorecard_path",
  "criteria": {
    "overall_status": "$overall_status",
    "performance_status": "$performance_status",
    "soak_status": "$soak_status",
    "soak_failures": $soak_failures,
    "soak_mesh_failures": $mesh_failures,
    "security_pass_rows": $security_pass_rows,
    "supply_chain_artifact_count": $supply_chain_artifact_count
  },
  "thresholds": {
    "max_soak_failures": $max_soak_failures,
    "max_mesh_failures": $max_mesh_failures,
    "min_security_pass_rows": $min_security_pass_rows,
    "min_supply_chain_artifacts": $min_supply_chain_artifacts
  },
  "rollback_triggers": $failure_json
}
EOF

cat > "$report_md" <<EOF
# Canary Criteria Report

Generated by \`tools/scripts/canary-criteria-check.sh\`.

## Result

- Status: \`$status\`
- Scorecard: \`$scorecard_path\`

## Criteria

| Criterion | Value | Threshold |
| --- | --- | --- |
| overall status | \`$overall_status\` | \`PASS\` |
| performance status | \`$performance_status\` | \`PASS\` |
| soak status | \`$soak_status\` | \`pass\` |
| soak failures | \`$soak_failures\` | \`<= $max_soak_failures\` |
| soak mesh failures | \`$mesh_failures\` | \`<= $max_mesh_failures\` |
| security checklist PASS rows | \`$security_pass_rows\` | \`>= $min_security_pass_rows\` |
| supply-chain artifact count | \`$supply_chain_artifact_count\` | \`>= $min_supply_chain_artifacts\` |

## Rollback Triggers

EOF

if [ "${#failures[@]}" -eq 0 ]; then
  {
    echo "- none"
  } >> "$report_md"
else
  for failure in "${failures[@]}"; do
    {
      echo "- $failure"
    } >> "$report_md"
  done
fi

echo "canary criteria report generated:"
echo "  - $report_md"
echo "  - $report_json"

if [ "$status" != "PASS" ]; then
  fail "rollback triggers met; see $report_json"
fi
