//! # interop-test
//!
//! Cross-implementation test harness for Python/Rust wire protocol interop.
//!
//! This crate provides utilities for:
//! - Loading binary test vectors generated by Python `styrene_wire.py`
//! - Validating that Rust produces byte-identical output
//! - Round-trip testing across implementations
//!
//! ## Test Fixtures
//!
//! Python scripts in `tests/interop/python/` generate binary fixtures
//! in `tests/interop/fixtures/`. Rust tests consume these fixtures.
//!
//! Run `just generate-fixtures` to regenerate from Python, then
//! `just test-interop` to validate.

/// Load a binary fixture file from the interop fixtures directory.
pub fn load_fixture(name: &str) -> Option<Vec<u8>> {
    let fixture_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../../tests/interop/fixtures")
        .join(name);
    std::fs::read(fixture_path).ok()
}
