#!/usr/bin/env python3
"""Tests for the human-attribution policy checker."""

from __future__ import annotations

import unittest

from check_human_attribution import SourceLine, added_lines, find_violations


class HumanAttributionTests(unittest.TestCase):
    def test_accepts_human_authorship_and_ordinary_generated_artifacts(self) -> None:
        lines = [
            SourceLine("message", 1, "Co-authored-by: Ada Lovelace <ada@example.com>"),
            SourceLine("fixture", 2, "Generated by the fixture builder."),
        ]

        self.assertEqual(find_violations(lines), [])

    def test_rejects_prohibited_names_case_insensitively(self) -> None:
        vendor = "Anth" + "ropic"
        assistant = "Clau" + "de"
        generated_with = "Generated " + "with"
        lines = [
            SourceLine("README.md", 4, f"{generated_with} {assistant} Code"),
            SourceLine("README.md", 8, f"See {vendor} documentation"),
        ]

        violations = find_violations(lines)

        self.assertEqual([violation.number for violation in violations], [4, 8])

    def test_rejects_generic_model_boilerplate_and_bot_trailers(self) -> None:
        generated = "A" + "I-generated"
        bot_name = "helper[" + "bot]"
        bot_email = "bot" + "@example.com"
        other_assistant = "Chat" + "GPT"
        lines = [
            SourceLine("message", 2, f"This file is {generated}."),
            SourceLine("message", 4, f"Co-authored-by: {bot_name} <{bot_email}>"),
            SourceLine("message", 5, f"Generated by {other_assistant}"),
        ]

        self.assertEqual(len(find_violations(lines)), 3)

    def test_extracts_only_added_lines_with_new_file_numbers(self) -> None:
        assistant = "Clau" + "de"
        generated_with = "generated " + "with"
        patch = "\n".join(
            [
                "diff --git a/notes.txt b/notes.txt",
                "--- a/notes.txt",
                "+++ b/notes.txt",
                "@@ -2 +2,3 @@",
                f"-old reference to {assistant}",
                "+ordinary replacement",
                f"+{generated_with} {assistant}",
                f"+++ {generated_with} {assistant}",
            ]
        )

        lines = list(added_lines(patch))

        self.assertEqual(
            lines,
            [
                SourceLine("notes.txt", 2, "ordinary replacement"),
                SourceLine("notes.txt", 3, f"{generated_with} {assistant}"),
                SourceLine("notes.txt", 4, f"++ {generated_with} {assistant}"),
            ],
        )
        self.assertEqual(len(find_violations(lines)), 2)


if __name__ == "__main__":
    unittest.main()
