//! Cross-language wire protocol interop tests.
//!
//! Reads binary fixtures generated by Python `generate_wire_fixtures.py`
//! and verifies Rust can decode them. This ensures byte-for-byte
//! compatibility between Python styrene_wire.py and Rust styrene-mesh.
//!
//! Run fixture generator first:
//!   python3 tests/interop/python/generate_wire_fixtures.py
//!
//! Then run these tests:
//!   cargo test -p styrene-mesh --test wire_interop

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use styrene_mesh::{StyreneMessage, StyreneMessageType};

fn fixture_dir() -> PathBuf {
    // CARGO_MANIFEST_DIR = crates/libs/styrene-mesh
    // Go up 3 levels to workspace root, then into tests/interop/fixtures
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent() // crates/libs
        .unwrap()
        .parent() // crates
        .unwrap()
        .parent() // workspace root
        .unwrap()
        .join("tests/interop/fixtures")
}

#[derive(serde::Deserialize)]
struct FixtureEntry {
    name: String,
    file: String,
    description: String,
    version: u8,
    message_type: u8,
    message_type_name: String,
    request_id_hex: Option<String>,
    payload_hex: String,
    wire_hex: String,
    wire_length: usize,
}

fn load_manifest() -> Vec<FixtureEntry> {
    let manifest_path = fixture_dir().join("wire_manifest.json");
    if !manifest_path.exists() {
        panic!(
            "Wire fixtures not found at {}. Run:\n  python3 tests/interop/python/generate_wire_fixtures.py",
            manifest_path.display()
        );
    }
    let data = fs::read_to_string(&manifest_path).expect("read manifest");
    serde_json::from_str(&data).expect("parse manifest")
}

fn load_fixture(entry: &FixtureEntry) -> Vec<u8> {
    let path = fixture_dir().join(&entry.file);
    fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

// ── V2 decode tests ──────────────────────────────────────────────────────────

#[test]
fn decode_all_v2_fixtures() {
    let entries = load_manifest();
    let v2_entries: Vec<_> = entries.iter().filter(|e| e.version == 2).collect();
    assert!(!v2_entries.is_empty(), "no v2 fixtures found");

    for entry in &v2_entries {
        let wire_bytes = load_fixture(entry);
        assert_eq!(wire_bytes.len(), entry.wire_length, "{}: file size mismatch", entry.name);

        let msg = StyreneMessage::decode(&wire_bytes).unwrap_or_else(|e| {
            panic!(
                "{} ({}): decode failed: {e}\n  wire_hex: {}",
                entry.name, entry.description, entry.wire_hex
            )
        });

        // Verify message type
        assert_eq!(
            msg.message_type as u8, entry.message_type,
            "{}: message_type mismatch (expected {} = {})",
            entry.name, entry.message_type_name, entry.message_type
        );

        // Verify version
        assert_eq!(msg.version, entry.version, "{}: version mismatch", entry.name);

        // Verify request_id
        if let Some(ref req_id_hex) = entry.request_id_hex {
            let expected_req_id = hex::decode(req_id_hex).expect("hex decode request_id");
            assert_eq!(
                msg.request_id.as_slice(),
                expected_req_id.as_slice(),
                "{}: request_id mismatch",
                entry.name
            );
        }

        // Verify payload
        let expected_payload = hex::decode(&entry.payload_hex).expect("hex decode payload");
        assert_eq!(msg.payload, expected_payload, "{}: payload mismatch", entry.name);

        eprintln!("  ✓ {} ({})", entry.name, entry.description);
    }

    eprintln!("  {} v2 fixtures verified", v2_entries.len());
}

// ── Roundtrip: decode Python → re-encode Rust → compare ─────────────────────

#[test]
fn roundtrip_v2_fixtures() {
    let entries = load_manifest();
    let v2_entries: Vec<_> = entries.iter().filter(|e| e.version == 2).collect();

    for entry in &v2_entries {
        let wire_bytes = load_fixture(entry);
        let msg = StyreneMessage::decode(&wire_bytes).expect("decode");
        let re_encoded = msg.encode();

        assert_eq!(
            re_encoded, wire_bytes,
            "{}: roundtrip mismatch — Rust re-encode differs from Python original\n  python: {}\n  rust:   {}",
            entry.name,
            hex::encode(&wire_bytes),
            hex::encode(&re_encoded),
        );

        eprintln!("  ✓ roundtrip {}", entry.name);
    }
}

// ── Specific message type decode checks ──────────────────────────────────────

#[test]
fn decode_ping_has_correct_type() {
    let entries = load_manifest();
    let ping = entries.iter().find(|e| e.name == "v2_ping_empty").expect("ping fixture");
    let wire = load_fixture(ping);
    let msg = StyreneMessage::decode(&wire).unwrap();
    assert_eq!(msg.message_type, StyreneMessageType::Ping);
    assert!(msg.payload.is_empty());
}

#[test]
fn decode_chat_has_payload() {
    let entries = load_manifest();
    let chat = entries.iter().find(|e| e.name == "v2_chat").expect("chat fixture");
    let wire = load_fixture(chat);
    let msg = StyreneMessage::decode(&wire).unwrap();
    assert_eq!(msg.message_type, StyreneMessageType::Chat);
    assert!(!msg.payload.is_empty());

    // Verify msgpack payload contains expected fields
    let payload: HashMap<String, rmpv::Value> =
        rmp_serde::from_slice(&msg.payload).expect("msgpack decode");
    assert!(payload.contains_key("text"));
    assert!(payload.contains_key("timestamp"));
}

#[test]
fn decode_no_correlation_has_zero_request_id() {
    let entries = load_manifest();
    let ann =
        entries.iter().find(|e| e.name == "v2_announce_no_correlation").expect("announce fixture");
    let wire = load_fixture(ann);
    let msg = StyreneMessage::decode(&wire).unwrap();
    assert_eq!(msg.request_id, [0u8; 16]);
}

#[test]
fn decode_large_payload() {
    let entries = load_manifest();
    let large = entries.iter().find(|e| e.name == "v2_chat_large").expect("large chat fixture");
    let wire = load_fixture(large);
    let msg = StyreneMessage::decode(&wire).unwrap();
    assert!(msg.payload.len() > 1000);
}

#[test]
fn decode_binary_payload() {
    let entries = load_manifest();
    let chunk =
        entries.iter().find(|e| e.name == "v2_file_chunk_binary").expect("file chunk fixture");
    let wire = load_fixture(chunk);
    let msg = StyreneMessage::decode(&wire).unwrap();
    assert_eq!(msg.payload.len(), 256);
    // Verify the raw bytes are 0x00..0xFF
    for (i, byte) in msg.payload.iter().enumerate() {
        assert_eq!(*byte, i as u8);
    }
}
