//! PQC session protocol payload types.
//!
//! These structs represent the msgpack-encoded payloads carried inside
//! `StyreneMessage` for PQC tunnel establishment. The wire format must
//! match Python `styrened`'s PQC session implementation byte-for-byte.

use serde::{Deserialize, Serialize};

/// Capability flags advertised during PQC negotiation.
///
/// Flags are bitwise-OR'd together in the `capabilities` field of
/// [`PqcCapabilityPayload`].
pub mod capability_flags {
    /// Peer does not support any tunnel backends.
    pub const TUNNEL_NONE: u8 = 0x00;
    /// Peer supports WireGuard tunnels.
    pub const TUNNEL_WG: u8 = 0x01;
    /// Peer supports strongSwan (IPsec + ML-KEM) tunnels.
    pub const TUNNEL_STRONGSWAN: u8 = 0x02;
    /// Peer supports either WireGuard or strongSwan.
    pub const TUNNEL_EITHER: u8 = TUNNEL_WG | TUNNEL_STRONGSWAN;
}

// ── Handshake payloads ──────────────────────────────────────────────────────

/// PQC session initiation (0xD0).
///
/// Sent by the initiator to begin a PQC handshake. Contains the initiator's
/// ephemeral X25519 public key and ML-KEM-768 encapsulation key.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PqcInitiatePayload {
    /// Protocol version for the PQC session (currently 1).
    pub version: u8,
    /// Session identifier (16 random bytes, generated by initiator).
    #[serde(with = "serde_bytes")]
    pub session_id: Vec<u8>,
    /// Initiator's ephemeral X25519 public key (32 bytes).
    #[serde(with = "serde_bytes")]
    pub x25519_public: Vec<u8>,
    /// Initiator's ML-KEM-768 encapsulation key (1184 bytes).
    #[serde(with = "serde_bytes")]
    pub mlkem_encapsulation_key: Vec<u8>,
    /// Initiator's RNS identity hash (for correlation, 16 bytes).
    #[serde(with = "serde_bytes")]
    pub identity_hash: Vec<u8>,
}

/// PQC session response (0xD1).
///
/// Sent by the responder after receiving a PqcInitiate. Contains the
/// responder's ephemeral X25519 public key, the ML-KEM ciphertext
/// (encapsulated shared secret), and an encrypted confirmation tag.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PqcRespondPayload {
    /// Must match the session_id from PqcInitiate.
    #[serde(with = "serde_bytes")]
    pub session_id: Vec<u8>,
    /// Responder's ephemeral X25519 public key (32 bytes).
    #[serde(with = "serde_bytes")]
    pub x25519_public: Vec<u8>,
    /// ML-KEM-768 ciphertext (1088 bytes) — encapsulated shared secret.
    #[serde(with = "serde_bytes")]
    pub mlkem_ciphertext: Vec<u8>,
    /// AES-256-GCM encrypted confirmation tag, using the derived hybrid key.
    /// Proves the responder has the correct shared secret.
    #[serde(with = "serde_bytes")]
    pub encrypted_confirm: Vec<u8>,
    /// Responder's RNS identity hash (16 bytes).
    #[serde(with = "serde_bytes")]
    pub identity_hash: Vec<u8>,
}

/// PQC session confirmation (0xD2).
///
/// Sent by the initiator after verifying the responder's encrypted_confirm.
/// Completes the 3-message handshake and establishes the session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PqcConfirmPayload {
    /// Must match the session_id from PqcInitiate.
    #[serde(with = "serde_bytes")]
    pub session_id: Vec<u8>,
    /// AES-256-GCM encrypted confirmation from initiator, proving mutual
    /// knowledge of the derived session key.
    #[serde(with = "serde_bytes")]
    pub encrypted_confirm: Vec<u8>,
}

// ── Session management payloads ─────────────────────────────────────────────

/// PQC session rekey (0xD3).
///
/// Sent by either side to perform a key ratchet step. Contains a new
/// ML-KEM encapsulation key or ciphertext for forward secrecy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PqcRekeyPayload {
    /// Must match the active session_id.
    #[serde(with = "serde_bytes")]
    pub session_id: Vec<u8>,
    /// Monotonic ratchet step counter. Must be greater than the last seen.
    pub ratchet_step: u64,
    /// New ephemeral X25519 public key (32 bytes).
    #[serde(with = "serde_bytes")]
    pub x25519_public: Vec<u8>,
    /// New ML-KEM-768 encapsulation key (1184 bytes) if initiating rekey,
    /// or ML-KEM-768 ciphertext (1088 bytes) if responding to rekey.
    #[serde(with = "serde_bytes")]
    pub mlkem_key_material: Vec<u8>,
    /// Whether this is an initiation (true) or response (false).
    pub is_initiation: bool,
}

/// PQC encrypted data frame (0xD4).
///
/// Carries application data encrypted with the current session key.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PqcDataPayload {
    /// Must match the active session_id.
    #[serde(with = "serde_bytes")]
    pub session_id: Vec<u8>,
    /// Monotonic sequence number for replay protection.
    pub sequence: u64,
    /// AES-256-GCM encrypted payload (nonce is derived from sequence).
    #[serde(with = "serde_bytes")]
    pub ciphertext: Vec<u8>,
}

/// PQC session close (0xD5).
///
/// Sent to gracefully terminate a PQC session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PqcClosePayload {
    /// Must match the active session_id.
    #[serde(with = "serde_bytes")]
    pub session_id: Vec<u8>,
    /// Reason code: 0 = normal, 1 = error, 2 = timeout, 3 = rekey_failure.
    pub reason: u8,
    /// Optional human-readable reason string.
    pub message: Option<String>,
}

// ── Capability negotiation payloads ─────────────────────────────────────────

/// PQC capability advertisement (0xD6).
///
/// Sent to advertise tunnel capabilities to a peer. Rides on the styrene
/// wire protocol layer (not RNS link context) to avoid upstream conflicts.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PqcCapabilityPayload {
    /// PQC protocol version supported (currently 1).
    pub pqc_version: u8,
    /// Bitfield of supported tunnel backends (see [`capability_flags`]).
    pub tunnel_capabilities: u8,
    /// IPv4 address for tunnel endpoint (4 bytes), if available.
    #[serde(with = "serde_bytes")]
    pub ipv4_endpoint: Option<Vec<u8>>,
    /// IPv6 address for tunnel endpoint (16 bytes), if available.
    #[serde(with = "serde_bytes")]
    pub ipv6_endpoint: Option<Vec<u8>>,
    /// UDP port for tunnel endpoint.
    pub tunnel_port: Option<u16>,
    /// Preferred MTU for the tunnel interface.
    pub mtu: Option<u16>,
}

/// PQC capability acknowledgment (0xD7).
///
/// Sent in response to a PqcCapability message, confirming the negotiated
/// tunnel type and endpoint information.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PqcCapabilityAckPayload {
    /// Agreed tunnel type (one of the [`capability_flags`] values).
    pub selected_tunnel: u8,
    /// Responder's IPv4 address for tunnel endpoint (4 bytes).
    #[serde(with = "serde_bytes")]
    pub ipv4_endpoint: Option<Vec<u8>>,
    /// Responder's IPv6 address for tunnel endpoint (16 bytes).
    #[serde(with = "serde_bytes")]
    pub ipv6_endpoint: Option<Vec<u8>>,
    /// Responder's UDP port for tunnel endpoint.
    pub tunnel_port: Option<u16>,
    /// Agreed MTU.
    pub mtu: Option<u16>,
}

/// PQC close reason codes.
pub mod close_reason {
    pub const NORMAL: u8 = 0;
    pub const ERROR: u8 = 1;
    pub const TIMEOUT: u8 = 2;
    pub const REKEY_FAILURE: u8 = 3;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn initiate_payload_roundtrip() {
        let payload = PqcInitiatePayload {
            version: 1,
            session_id: vec![0xAB; 16],
            x25519_public: vec![0x01; 32],
            mlkem_encapsulation_key: vec![0x02; 1184],
            identity_hash: vec![0x03; 16],
        };
        let encoded = rmp_serde::to_vec(&payload).expect("encode");
        let decoded: PqcInitiatePayload = rmp_serde::from_slice(&encoded).expect("decode");
        assert_eq!(decoded.version, 1);
        assert_eq!(decoded.session_id.len(), 16);
        assert_eq!(decoded.x25519_public.len(), 32);
        assert_eq!(decoded.mlkem_encapsulation_key.len(), 1184);
        assert_eq!(decoded.identity_hash.len(), 16);
    }

    #[test]
    fn respond_payload_roundtrip() {
        let payload = PqcRespondPayload {
            session_id: vec![0xAB; 16],
            x25519_public: vec![0x01; 32],
            mlkem_ciphertext: vec![0x02; 1088],
            encrypted_confirm: vec![0x03; 44], // 12 nonce + 16 tag + 16 data
            identity_hash: vec![0x04; 16],
        };
        let encoded = rmp_serde::to_vec(&payload).expect("encode");
        let decoded: PqcRespondPayload = rmp_serde::from_slice(&encoded).expect("decode");
        assert_eq!(decoded.mlkem_ciphertext.len(), 1088);
    }

    #[test]
    fn confirm_payload_roundtrip() {
        let payload =
            PqcConfirmPayload { session_id: vec![0xAB; 16], encrypted_confirm: vec![0x03; 44] };
        let encoded = rmp_serde::to_vec(&payload).expect("encode");
        let decoded: PqcConfirmPayload = rmp_serde::from_slice(&encoded).expect("decode");
        assert_eq!(decoded.session_id.len(), 16);
    }

    #[test]
    fn data_payload_roundtrip() {
        let payload = PqcDataPayload {
            session_id: vec![0xAB; 16],
            sequence: 42,
            ciphertext: vec![0xFF; 256],
        };
        let encoded = rmp_serde::to_vec(&payload).expect("encode");
        let decoded: PqcDataPayload = rmp_serde::from_slice(&encoded).expect("decode");
        assert_eq!(decoded.sequence, 42);
    }

    #[test]
    fn close_payload_roundtrip() {
        let payload = PqcClosePayload {
            session_id: vec![0xAB; 16],
            reason: close_reason::NORMAL,
            message: Some("done".into()),
        };
        let encoded = rmp_serde::to_vec(&payload).expect("encode");
        let decoded: PqcClosePayload = rmp_serde::from_slice(&encoded).expect("decode");
        assert_eq!(decoded.reason, 0);
        assert_eq!(decoded.message.as_deref(), Some("done"));
    }

    #[test]
    fn capability_payload_roundtrip() {
        let payload = PqcCapabilityPayload {
            pqc_version: 1,
            tunnel_capabilities: capability_flags::TUNNEL_EITHER,
            ipv4_endpoint: Some(vec![192, 168, 1, 1]),
            ipv6_endpoint: None,
            tunnel_port: Some(4500),
            mtu: Some(1420),
        };
        let encoded = rmp_serde::to_vec(&payload).expect("encode");
        let decoded: PqcCapabilityPayload = rmp_serde::from_slice(&encoded).expect("decode");
        assert_eq!(decoded.tunnel_capabilities, capability_flags::TUNNEL_EITHER);
        assert_eq!(decoded.tunnel_port, Some(4500));
    }

    #[test]
    fn capability_ack_payload_roundtrip() {
        let payload = PqcCapabilityAckPayload {
            selected_tunnel: capability_flags::TUNNEL_STRONGSWAN,
            ipv4_endpoint: Some(vec![10, 0, 0, 1]),
            ipv6_endpoint: None,
            tunnel_port: Some(500),
            mtu: Some(1400),
        };
        let encoded = rmp_serde::to_vec(&payload).expect("encode");
        let decoded: PqcCapabilityAckPayload = rmp_serde::from_slice(&encoded).expect("decode");
        assert_eq!(decoded.selected_tunnel, capability_flags::TUNNEL_STRONGSWAN);
    }

    #[test]
    fn rekey_payload_roundtrip() {
        let payload = PqcRekeyPayload {
            session_id: vec![0xAB; 16],
            ratchet_step: 1,
            x25519_public: vec![0x01; 32],
            mlkem_key_material: vec![0x02; 1184],
            is_initiation: true,
        };
        let encoded = rmp_serde::to_vec(&payload).expect("encode");
        let decoded: PqcRekeyPayload = rmp_serde::from_slice(&encoded).expect("decode");
        assert_eq!(decoded.ratchet_step, 1);
        assert!(decoded.is_initiation);
    }
}
